"""Add profession column to users

Revision ID: 08eb3193f281
Revises: 1f95ad8ccb70
Create Date: 2026-05-31 13:25:03.651378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08eb3193f281'
down_revision: Union[str, None] = '1f95ad8ccb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'EMPLOYEE', name='userrole'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('ADMIN', 'EMPLOYEE', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
